# Generated by Django 6.0.2 on 2026-03-04 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalStore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("domain", models.CharField(max_length=100)),
                ("icon_url", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "external_stores",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "장르",
                "verbose_name_plural": "장르들",
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("icon_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "플랫폼",
                "verbose_name_plural": "플랫폼들",
                "db_table": "platforms",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그들",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField(unique=True)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("search_vector", models.TextField(blank=True, null=True)),
                ("released", models.DateField(blank=True, null=True)),
                ("tba", models.BooleanField(default=False)),
                ("thumbnail_img_url", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255)),
                ("rawg_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("rawg_ratings_count", models.IntegerField(default=0)),
                ("metacritic", models.SmallIntegerField(blank=True, null=True)),
                ("rawg_added", models.IntegerField(default=0)),
                ("playtime", models.IntegerField(default=0)),
                ("esrb_rating", models.CharField(default="unknown", max_length=20)),
                ("age_rating_min", models.SmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("rawg_updated", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "games",
                "indexes": [
                    models.Index(fields=["age_rating_min"], name="IDX_games_age_rating"),
                    models.Index(fields=["rawg_rating"], name="IDX_games_rawg_rating"),
                    models.Index(fields=["rawg_added"], name="IDX_games_rawg_added"),
                    models.Index(fields=["released"], name="IDX_games_released"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GameMedia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rawg_id", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(choices=[("screenshot", "스크린샷"), ("trailer", "트레일러")], max_length=20),
                ),
                ("media_url", models.CharField(max_length=255)),
                ("data_480", models.CharField(default="", max_length=255)),
                ("data_max", models.CharField(default="", max_length=255)),
                ("video_name", models.CharField(default="", max_length=200)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media", to="games.game"
                    ),
                ),
            ],
            options={
                "db_table": "game_media",
                "unique_together": {("game", "rawg_id")},
            },
        ),
        migrations.CreateModel(
            name="GameStore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_stores", to="games.game"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stores",
                        to="games.externalstore",
                    ),
                ),
            ],
            options={
                "db_table": "game_stores",
                "unique_together": {("game", "store")},
            },
        ),
        migrations.CreateModel(
            name="GameGenre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_genres", to="games.game"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_genres", to="games.genre"
                    ),
                ),
            ],
            options={
                "db_table": "game_genres",
                "unique_together": {("game", "genre")},
            },
        ),
        migrations.CreateModel(
            name="GamePlatform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requirements_minimum", models.TextField(blank=True, default="")),
                ("requirements_recommended", models.TextField(blank=True, default="")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_platforms", to="games.game"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_platforms", to="games.platform"
                    ),
                ),
            ],
            options={
                "db_table": "game_platforms",
                "unique_together": {("game", "platform")},
            },
        ),
        migrations.CreateModel(
            name="GameTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_tags", to="games.game"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="game_tags", to="games.tag"
                    ),
                ),
            ],
            options={
                "db_table": "game_tags",
                "unique_together": {("game", "tag")},
            },
        ),
    ]
