# Generated by Django 6.0.2 on 2026-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemedia",
            name="data_480",
        ),
        migrations.RemoveField(
            model_name="gamemedia",
            name="data_max",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="video_url_480",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamemedia",
            name="video_url_max",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="gamemedia",
            name="video_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
