# Generated by Django 6.0.2 on 2026-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_gamemedia_data_480_remove_gamemedia_data_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="esrb_rating",
            field=models.CharField(
                choices=[
                    ("everyone", "전체 이용가"),
                    ("everyone_10_plus", "10세 이상"),
                    ("teen", "13세 이상"),
                    ("mature", "17세 이상"),
                    ("adults_only", "성인 전용"),
                    ("rating_pending", "심의 예정"),
                    ("unknown", "미분류"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
