# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_game_esrb_rating"),
    ]

    operations = [
        # 인덱스 제거
        migrations.RemoveIndex(
            model_name="game",
            name="IDX_games_age_rating",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="IDX_games_rawg_rating",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="IDX_games_rawg_added",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="IDX_games_released",
        ),
        # unique_together 해제 먼저 (FK 삭제 전에)
        migrations.AlterUniqueTogether(
            name="gamegenre",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="gameplatform",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="gamestore",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="gametag",
            unique_together=None,
        ),
        # 그 다음 FK 필드 삭제
        migrations.RemoveField(
            model_name="gamegenre",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamegenre",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="gametag",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gametag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="gameplatform",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gameplatform",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="gamestore",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamestore",
            name="store",
        ),
        migrations.DeleteModel(
            name="GameMedia",
        ),
    ]
