# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_remove_game_idx_games_age_rating_and_more"),
        ("interactions", "0004_remove_interactionlog_interaction_game_id_43dbe2_idx_and_more"),
        ("preferences", "0002_remove_usergameaffinity_unique_user_game_affinity_and_more"),
        ("recommendations", "0003_remove_gamesimilarity_unique_game_similarity_pair_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="GameGenre",
        ),
        migrations.DeleteModel(
            name="GamePlatform",
        ),
        migrations.DeleteModel(
            name="GameStore",
        ),
        migrations.DeleteModel(
            name="GameTag",
        ),
    ]
