# Generated by Django 6.0.2 on 2026-03-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_delete_game_delete_gamegenre_delete_gameplatform_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={},
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RemoveField(
            model_name="genre",
            name="rawg_id",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="icon_url",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="rawg_id",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="rawg_id",
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="igdb_type",
            field=models.CharField(choices=[("genre", "Genre"), ("theme", "Theme")], default="genre", max_length=10),
        ),
        migrations.AddField(
            model_name="platform",
            name="igdb_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="igdb_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="igdb_type",
            field=models.CharField(
                choices=[("theme", "Theme"), ("keyword", "Keyword"), ("game_mode", "Game Mode")],
                default="theme",
                max_length=10,
            ),
        ),
    ]
