# Generated by Django 6.0.2 on 2026-03-17 04:51

from django.db import migrations, models

GENRES = [
    {"igdb_id": 12, "igdb_type": "genre", "name": "RPG", "slug": "rpg"},
    {"igdb_id": 1, "igdb_type": "theme", "name": "액션", "slug": "action"},
    {"igdb_id": 31, "igdb_type": "genre", "name": "어드벤처", "slug": "adventure"},
    {"igdb_id": 5, "igdb_type": "genre", "name": "FPS", "slug": "shooter"},
    {"igdb_id": 15, "igdb_type": "genre", "name": "전략", "slug": "strategy"},
    {"igdb_id": 13, "igdb_type": "genre", "name": "시뮬레이션", "slug": "simulator"},
    {"igdb_id": 14, "igdb_type": "genre", "name": "스포츠", "slug": "sport"},
    {"igdb_id": 10, "igdb_type": "genre", "name": "레이싱", "slug": "racing"},
    {"igdb_id": 9, "igdb_type": "genre", "name": "퍼즐", "slug": "puzzle"},
    {"igdb_id": 5, "igdb_type": "game_mode", "name": "MMORPG", "slug": "mmorpg"},
]

PLATFORMS = [
    {"igdb_id": 6, "name": "PC", "slug": "pc"},
    {"igdb_id": 167, "name": "PlayStation", "slug": "playstation"},
    {"igdb_id": 169, "name": "Xbox", "slug": "xbox"},
    {"igdb_id": 130, "name": "Nintendo Switch", "slug": "nintendo-switch"},
    {"igdb_id": 34, "name": "Mobile", "slug": "mobile"},
]

TAGS = [
    {"igdb_id": 38, "igdb_type": "theme", "name": "오픈월드", "slug": "open-world"},
    {"igdb_id": 2426, "igdb_type": "keyword", "name": "스토리 중심", "slug": "story-rich"},
    {"igdb_id": 3, "igdb_type": "game_mode", "name": "Co-op", "slug": "co-op"},
    {"igdb_id": 546, "igdb_type": "keyword", "name": "PvP", "slug": "pvp"},
    {"igdb_id": 1, "igdb_type": "game_mode", "name": "싱글플레이", "slug": "single-player"},
    {"igdb_id": 2, "igdb_type": "game_mode", "name": "멀티플레이", "slug": "multiplayer"},
    {"igdb_id": 21, "igdb_type": "theme", "name": "생존", "slug": "survival"},
    {"igdb_id": 19, "igdb_type": "theme", "name": "공포", "slug": "horror"},
    {"igdb_id": 17, "igdb_type": "theme", "name": "판타지", "slug": "fantasy"},
    {"igdb_id": 18, "igdb_type": "theme", "name": "SF", "slug": "science-fiction"},
]


def seed(apps, schema_editor):
    Genre = apps.get_model("games", "Genre")
    Platform = apps.get_model("games", "Platform")
    Tag = apps.get_model("games", "Tag")

    for g in GENRES:
        Genre.objects.get_or_create(slug=g["slug"], defaults=g)
    for p in PLATFORMS:
        Platform.objects.get_or_create(slug=p["slug"], defaults=p)
    for t in TAGS:
        Tag.objects.get_or_create(slug=t["slug"], defaults=t)


def unseed(apps, schema_editor):
    Genre = apps.get_model("games", "Genre")
    Platform = apps.get_model("games", "Platform")
    Tag = apps.get_model("games", "Tag")
    Genre.objects.all().delete()
    Platform.objects.all().delete()
    Tag.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_alter_genre_options_alter_platform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="igdb_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tag",
            name="igdb_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(fields=("igdb_id", "igdb_type"), name="unique_genre_igdb"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(fields=("igdb_id", "igdb_type"), name="unique_tag_igdb"),
        ),
        migrations.RunPython(seed, unseed),
    ]
