# Generated by Django 6.0.2 on 2026-03-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_gamemedia_data_480_remove_gamemedia_data_max_and_more"),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interactioncontextrule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="interactionlog",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="interactionweightrule",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="interactionlog",
            name="game",
            field=models.ForeignKey(
                blank=True, db_column="game_id", null=True, on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
    ]
