# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_remove_game_idx_games_age_rating_and_more"),
        ("interactions", "0003_interactionlog_store_and_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interactionlog",
            name="interaction_game_id_43dbe2_idx",
        ),
        migrations.RenameIndex(
            model_name="interactionlog",
            new_name="interaction_store_i_b7362b_idx",
            old_name="interaction_store_i_4e10f0_idx",
        ),
        migrations.AddField(
            model_name="interactionlog",
            name="igdb_game_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, help_text="IGDB 게임 ID (외부 API 기준)", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="interactionlog",
            index=models.Index(fields=["igdb_game_id"], name="interaction_igdb_ga_843caa_idx"),
        ),
        migrations.RemoveField(
            model_name="interactionlog",
            name="game",
        ),
    ]
