# Generated by Django 6.0.2 on 2026-03-04 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserGameAffinity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "like_state",
                    models.SmallIntegerField(choices=[(-1, "싫어요"), (0, "중립"), (1, "좋아요")], default=0),
                ),
                ("preference_score", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("last_interacted_at", models.DateTimeField()),
                ("calculated_at", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        db_column="game_id", on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_game_affinity",
                "indexes": [
                    models.Index(fields=["user"], name="user_game_a_user_id_c5be66_idx"),
                    models.Index(fields=["game"], name="user_game_a_game_id_ca1712_idx"),
                    models.Index(fields=["like_state"], name="user_game_a_like_st_197974_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("user", "game"), name="unique_user_game_affinity")],
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceGenre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "genre",
                    models.ForeignKey(
                        db_column="genre_id", on_delete=django.db.models.deletion.CASCADE, to="games.genre"
                    ),
                ),
                (
                    "user_preference",
                    models.ForeignKey(
                        db_column="user_preference_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.userpreference",
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences_genres",
                "indexes": [
                    models.Index(fields=["user_preference"], name="user_prefer_user_pr_aacfc5_idx"),
                    models.Index(fields=["genre"], name="user_prefer_genre_i_3e8c95_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_preference", "genre"), name="unique_user_preference_genre")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPreferencePlatform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.ForeignKey(
                        db_column="platform_id", on_delete=django.db.models.deletion.CASCADE, to="games.platform"
                    ),
                ),
                (
                    "user_preference",
                    models.ForeignKey(
                        db_column="user_preference_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.userpreference",
                    ),
                ),
            ],
            options={
                "db_table": "user_preference_platforms",
                "indexes": [
                    models.Index(fields=["user_preference"], name="user_prefer_user_pr_f9f253_idx"),
                    models.Index(fields=["platform"], name="user_prefer_platfor_4e9176_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_preference", "platform"), name="unique_user_preference_platform"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tag",
                    models.ForeignKey(db_column="tag_id", on_delete=django.db.models.deletion.CASCADE, to="games.tag"),
                ),
                (
                    "user_preference",
                    models.ForeignKey(
                        db_column="user_preference_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.userpreference",
                    ),
                ),
            ],
            options={
                "db_table": "user_preference_tags",
                "indexes": [
                    models.Index(fields=["user_preference"], name="user_prefer_user_pr_31ade7_idx"),
                    models.Index(fields=["tag"], name="user_prefer_tag_id_bf643f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_preference", "tag"), name="unique_user_preference_tag")
                ],
            },
        ),
    ]
