# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usergameaffinity",
            name="unique_user_game_affinity",
        ),
        migrations.RemoveIndex(
            model_name="usergameaffinity",
            name="user_game_a_game_id_ca1712_idx",
        ),
        migrations.AddField(
            model_name="usergameaffinity",
            name="igdb_game_id",
            field=models.BigIntegerField(db_index=True, default=0, help_text="IGDB 게임 ID (외부 API 기준)"),
        ),
        migrations.AddIndex(
            model_name="usergameaffinity",
            index=models.Index(fields=["igdb_game_id"], name="user_game_a_igdb_ga_1da653_idx"),
        ),
        migrations.AddConstraint(
            model_name="usergameaffinity",
            constraint=models.UniqueConstraint(fields=("user", "igdb_game_id"), name="unique_user_game_affinity"),
        ),
        migrations.RemoveField(
            model_name="usergameaffinity",
            name="game",
        ),
    ]
