services:
  django:
    container_name: django-prod
    image: ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/staticfiles
    # Nginx 사용하면 이거 주석 해제하고 ports 삭제
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ../envs/.prod.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery-worker:
    container_name: celery-worker-prod
    image: ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    command: celery -A config worker -l info
    env_file:
      - ../envs/.prod.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery-beat:
    image: ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    container_name: celery-beat-prod
    command: celery -A config beat -l info
    env_file:
      - ../envs/.prod.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # nginx 미사용 (조교님 세팅 기준)
  # nginx:
  #   image: ${ECR_REGISTRY}/gechu-nginx:${IMAGE_TAG}
  #   build:
  #     context: ..
  #     dockerfile: resources/nginx/prod.Dockerfile
  #   container_name: nginx-prod
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - static_volume:/app/staticfiles:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro        # certbot SSL 인증서
  #     - /var/www/certbot:/var/www/certbot:ro         # certbot 인증 챌린지
  #   depends_on:
  #     - django
  #   restart: unless-stopped

volumes:
  postgres_prod_data:
  static_volume:
