# Generated by Django 6.0.2 on 2026-03-04 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesimilarity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recommendationjob",
            name="updated_at",
        ),
    ]
