# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_remove_gamesimilarity_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gamesimilarity",
            name="unique_game_similarity_pair",
        ),
        migrations.RemoveConstraint(
            model_name="userrecommendation",
            name="unique_user_game_recommendation",
        ),
        migrations.RemoveIndex(
            model_name="gamesimilarity",
            name="game_simila_game_id_9349d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="gamesimilarity",
            name="game_simila_similar_3a0e90_idx",
        ),
        migrations.AddField(
            model_name="gamesimilarity",
            name="igdb_game_id",
            field=models.BigIntegerField(db_index=True, default=0, help_text="IGDB 게임 ID"),
        ),
        migrations.AddField(
            model_name="gamesimilarity",
            name="igdb_similar_game_id",
            field=models.BigIntegerField(db_index=True, default=0, help_text="유사 게임 IGDB ID"),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="igdb_game_id",
            field=models.BigIntegerField(db_index=True, default=0, help_text="IGDB 게임 ID"),
        ),
        migrations.AddIndex(
            model_name="gamesimilarity",
            index=models.Index(fields=["igdb_game_id"], name="game_simila_igdb_ga_174c18_idx"),
        ),
        migrations.AddIndex(
            model_name="gamesimilarity",
            index=models.Index(fields=["igdb_similar_game_id"], name="game_simila_igdb_si_b4d32a_idx"),
        ),
        migrations.AddConstraint(
            model_name="gamesimilarity",
            constraint=models.UniqueConstraint(
                fields=("igdb_game_id", "igdb_similar_game_id"), name="unique_game_similarity_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrecommendation",
            constraint=models.UniqueConstraint(fields=("user", "igdb_game_id"), name="unique_user_game_recommendation"),
        ),
        migrations.RemoveField(
            model_name="userrecommendation",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamesimilarity",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamesimilarity",
            name="similar_game",
        ),
    ]
