# Generated by Django 6.0.2 on 2026-03-04 02:07

import apps.users.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("birth_date", models.DateField()),
                ("profile_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_adult_verified", models.BooleanField(default=False)),
                ("adult_verified_at", models.DateTimeField(blank=True, null=True)),
                ("adult_verification_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", apps.users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdultVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("BBATON", "비바톤")], max_length=20)),
                (
                    "provider_uid",
                    models.CharField(help_text="인증 제공자 내부 사용자 식별자. 로그인 계정과 무관", max_length=255),
                ),
                (
                    "raw_payload",
                    models.JSONField(blank=True, help_text="인증 응답 원본 저장 (디버깅/분쟁 대응용)", null=True),
                ),
                ("verified_at", models.DateTimeField(help_text="성인 인증이 실제 수행된 시각(event time)")),
                ("expires_at", models.DateTimeField(help_text="verified_at + 정책 기간")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adult_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "adult_verifications",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("KAKAO", "카카오"), ("DISCORD", "디스코드")], max_length=20)),
                ("provider_uid", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
                "unique_together": {("provider", "provider_uid")},
            },
        ),
    ]
