# Generated by Django 6.0.2 on 2026-03-19 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_superuser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="socialuser",
            unique_together={("provider", "provider_uid"), ("user", "provider")},
        ),
    ]
